---
- name: Restart NetworkManager service
  systemd:
    name: NetworkManager
    enabled: true
    state: restarted
  become: true

- name: Reset interface
  block:
  - name: Bring interface down
    shell: ifdown ib0
  - name: Unload kernel modules
    modprobe:
      name: "{{ item }}"
      state: absent
    with_items: "{{ ib_modules }}"
    ignore_errors: true
  - name: Load kernel modules
    modprobe:
      name: "{{ item }}"
      state: present
    with_items: "{{ ib_modules }}"
  - name: Bring interface up
    shell: ifup ib0
...
