---
# Kubernetes
cluster_service: container-infra
cluster_user: "fedora"
cluster_state: "present"
cluster_name: "kubernetes"
cluster_template_name: "k8s-fedora-atomic-29"
cluster_keypair: "wendy"
cluster_coe: "kubernetes"
cluster_default_interface: "{{ ext_name }}"
cluster_interfaces:
- "{{ ext_name }}"
- "{{ lln_name }}"
- "{{ bdn_name }}"

cluster_master_count: 1
cluster_master_group:
  name: "master"
  count: "{{ cluster_master_count }}"

cluster_worker_count: 6
cluster_worker_group:
  name: "minion"
  count: "{{ cluster_worker_count }}"

cluster_groups:
- "{{ cluster_master_group }}"
- "{{ cluster_worker_group }}"

cluster_roles:
- name: "kubernetes"
  groups: "{{ cluster_groups }}"

# Kubernetes gluster source and mount path
gluster_src: 10.3.0.12:/swarm_vol
gluster_mnt: /mnt/gluster

# Kubernetes config for Ceph mount
ceph_mount_enabled: false
ceph_mount_fuse: false

# The user is fedora for Kubernetes and Docker Swarm container clusters.
alaska_admin_user: fedora
...
