---
- hosts:
  - cluster_beegfs_mgmt
  - cluster_beegfs_mds
  - cluster_beegfs_oss
  - cluster_beegfs_client
  roles:
    - role: stackhpc.beegfs
      beegfs_enable:
        admon: false
        mgmt: "{{ inventory_hostname in groups['cluster_beegfs_mgmt'] | default([]) }}"
        meta: "{{ inventory_hostname in groups['cluster_beegfs_mds'] | default([]) }}"
        oss: "{{ inventory_hostname in groups['cluster_beegfs_oss'] | default([]) }}"
        tuning: "{{ inventory_hostname in groups['cluster_beegfs_oss'] | default([]) }}"
        client: "{{ inventory_hostname in groups['cluster_beegfs_client'] | default([]) }}"
...
