#
# Copyright StackHPC, 2018
#
---
# Add cluster nodes to SSH known hosts
- import_playbook: ssh-known-hosts.yml
  when: ssh_known_hosts_enable

# Query OpenStack Manila for details aob
- hosts: localhost
  roles:
    - role: stackhpc.os-manila-mount
      vars:
        os_manila_mount_action: "lookup"
        os_manila_mount_share_name: "{{ ceph_mount_share_name }}"
        os_manila_mount_auth: "{{ openstack_auth }}"

- hosts: cluster
  roles:
    # Perform the mount action on all Ceph client nodes
    - role: stackhpc.os-manila-mount
      os_manila_mount_action: "mount"
      os_manila_mount_host: "{{ hostvars['localhost']['os_manila_mount_host'] }}"
      os_manila_mount_access_key: "{{ hostvars['localhost']['os_manila_mount_access_key'] }}"
      os_manila_mount_export: "{{ hostvars['localhost']['os_manila_mount_export'] }}"
      os_manila_mount_pkgs_install: True
      os_manila_mount_path: "{{ ceph_mount_path }}"
      os_manila_mount_user: "root"
      os_manila_mount_group: "root"
      os_manila_mount_fuse: "{{ ceph_mount_fuse | default(False) }}"
      os_manila_mount_auth: "{{ openstack_auth }}"

- hosts: cluster
  gather_facts: yes
  pre_tasks:
  - name: Enable passwordless sudo for wheel group
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'    
    become: yes
  - name: Set sysctl settings based on SIP team request
    sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      state: present
      reload: yes
      sysctl_set: yes
    with_items:
      - { name: net.core.rmem_max, value: 33554432 }
      - { name: net.core.rmem_default, value: 8388608 }
      - { name: net.core.wmem_max, value: 524288 }
      - { name: net.core.wmem_default, value: 524288 }
    become: yes
  roles:
  # Configure infiniband interface
  - configure_ib
  # Mount gluster volume on 
  - role: mount_glusterfs
    when:
    - gluster_src is defined
    - gluster_src is not none
  # Perform the mount action on all Ceph client nodes
  - { role: singleplatform-eng.users, become: yes }
...
