#
# Copyright StackHPC, 2018
#
---
- hosts: openstack
  gather_facts: no
  roles:
  - role: stackhpc.os-container-infra
    os_container_infra_cloud: "{{ openstack_cloud }}"
    os_container_infra_auth: "{{ openstack_auth }}"
    os_container_infra_auth_type: "{{ openstack_auth_type }}"
    os_container_infra_cluster_name: "{{ cluster_name }}"
    os_container_infra_state: "{{ cluster_state | default('query') }}"
    os_container_infra_user: "{{ cluster_user }}"
    os_container_infra_cluster_template_name: "{{ cluster_template_name }}"
    os_container_infra_roles: "{{ cluster_roles }}"
    os_container_infra_keypair: "{{ cluster_keypair }}"
    os_container_infra_default_interface: "{{ cluster_default_interface }}"
    os_container_infra_interfaces: "{{ cluster_interfaces | default(omit) }}"
    os_container_infra_master_group: "{{ cluster_master_group }}"
    os_container_infra_worker_group: "{{ cluster_worker_group }}"
    os_container_infra_coe: "{{ cluster_coe }}"
    os_container_infra_environment_group: "{{ cluster_environment_group }}"
...
