---
# Example module for extracting details about a Manila-managed shared filesystem
# and mounting it on a group of client compute nodes

# Query OpenStack Manila for details aob
- hosts: openstack
  roles:
    - role: stackhpc.os-manila-mount
      os_manila_mount_action: "lookup"
      os_manila_mount_share_name: "{{ ceph_mount_share_name }}"
      os_manila_mount_auth: "{{ openstack_auth }}"
      os_manila_mount_auth_type: "{{ openstack_auth_type }}"
      os_manila_mount_os_config_name: "{{ openstack_cloud }}"

- hosts: cluster_ceph_client
  roles:
    # Perform the mount action on all Ceph client nodes
    - role: stackhpc.os-manila-mount
      os_manila_mount_action: "mount"
      os_manila_mount_host: "{{ hostvars['localhost']['os_manila_mount_host'] }}"
      os_manila_mount_access_key: "{{ hostvars['localhost']['os_manila_mount_access_key'] }}"
      os_manila_mount_export: "{{ hostvars['localhost']['os_manila_mount_export'] }}"
      os_manila_mount_pkgs_install: True
      os_manila_mount_path: "{{ alaska_homedir }}"
      os_manila_mount_user: "root"
      os_manila_mount_group: "root"
      os_manila_mount_fuse: "{{ ceph_mount_fuse | default(True) }}"
      os_manila_mount_auth: "{{ openstack_auth }}"
      os_manila_mount_auth_type: "{{ openstack_auth_type }}"
      os_manila_mount_os_config_name: "{{ openstack_cloud }}"
